### ISSUE TITLE
Top questions 

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#2] opened 2017-03-02 14:58 UTC
Answering these will help get the project off to a strong start (please edit @mvl22 and @mem48 ):

- [ ] What public transport data is known?

**Comment by mem48** [comment] 2017-03-03 10:02
My first thoughts on some technical challenges that we need to deal with:

**1) Infrastructure Identification**

- [ ]  Where are cycle lanes (is OSM complete)
- [ ] Where are bus lanes
- [ ] Where are cycle-friendly junctions

**2) Converting PCT Flow results to road segment attributes**

The PCT LSOA level results (see http://npct0.vs.mythic-beasts.com/m/?r=cambridgeshire then select route network LSOA) are a raster with 10m pixels counting the number of cyclists. The lines are typically 2-3 pixels wide and can have some artifacts with lower values around the edges.  

- [ ] How to convert raster values to attributes of the vector road network

**3) Converting the number of cyclists on a road to an infrastructure requirement**

PCT data counts the number of cyclists (in both directions) commuting along each road. Thus it is a rough measure of the number of commuter cyclists you would see during rush hour on a weekday. This excludes all other reasons for cycling, but is the only data we have. CyIPT is based on the assumption that more cyclists means a need for better infrastructure.

- [ ] How many cyclists requires a cycle lane
- [ ] What are the thresholds for different styles of cycle lane (standard, superhighway, segregated, etc?)
- [ ] What are the thresholds for different junction interventions
- [ ] How is the cycle infrastructure requirement linked to road type, e.g. a quite residential road may not require a cycle lane regardless how many cyclists use it
- [ ] How do we know/estimate the motorized traffic levels on each road

**4) How suitable is a road for new cycling infrastructure**

Not every road that may need cycling infrastructure may be capable of accommodating it

- [ ] What physical constraints are there on cycling infrastructure
- [ ] How can we  determine the widths of roads/paths
- [ ] What are the physical thresholds on for different types of infrastructure

**5) How to cost cycling infrastructure**

- [ ] What affects the cost of cycling infrastructure other than type and length
- [ ] How to reasonably group interventions (i.e. we don't want the type of cycle lane changing every 100m, proposed interventions must have plausible designs)

**6) How to reroute cyclists on new infrastructure**

Part of the logic of CyIPT is that new infrastructure does not just benefit current cyclists but will also attract new cyclists, thus we need to model mode shift caused by new infrastructure

- [ ] How to model the mode share based on current/future cycling infrastructure (cycle streets business score?)
- [ ] How do we handle rerouting and rerunning the mode share calculations for potential thousands of different interventions
- [ ] How do we consider batches of interventions that are greater than the sum of their parts
- [ ] How do we handle new infrastructure drawing cyclists of other routes, i.e. one piece of infrastructure undermining the case for another.

**7) How to evaluate benefits**

Assuming we know the cost and the change in number of cyclists

- [ ] How can we do a simple cost-benefit calculation
- [ ] What does it depend on and do we have all the data we need

**8) General Technical Questions**

- [ ] Routing via cyclestreets.net is slow, we may need a local setup at Leeds to perform all the routing required
- [ ] We can't redo the whole country every time we change a single road, so some regionalisation is required, the PCT regions were sub-optimal as there were lots of cross-regional flows that were excluded can we do better

**Comment by mem48** [comment] 2017-05-05 18:25
Closing as we have moved past general questions

**Closed as completed by mem48** 2017-05-05 18:25 UTC

**Comment by Robinlovelace** [comment] 2017-05-10 15:53
Just adding it here as it's a point of discussion, mostly of interest to @mem48 but maybe @mvl22 also. How to best visualise the results? 3d is increasingly an option: http://giscience.github.io/GIScene.js/examples/dem_mapTile_overlay.html Not an issue or priority hence dumped here.
