### ISSUE TITLE
How to segment roads

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#12] opened 2017-03-21 15:58 UTC

**Comment by Robinlovelace** [comment] 2017-03-21 15:58
Suggestion: use OSM tags/relations as a starting point.

**Comment by Robinlovelace** [comment] 2017-03-21 16:15
Happy for others to work on this - we need example data for this to work.

**Comment by mem48** [comment] 2017-04-19 19:27
Duplicate of other issues e.g. #26

**Closed as completed by mem48** 2017-04-19 19:27 UTC
